### ISSUE TITLE
viewModel.hasChanges not dependant on all editables

### ISSUE THREAD

**Issue by Brendan-csel** [romanych/ko.editables#8]
Thanks for this project.  A question...

The code for viewModel.hasChanges uses ko.utils.arrayFirst to find the first editable that has changed.  As it iterates through those editables it will create a dependency on them so that the viewModel.hasChanges will be updated if any editable.hasChanges is modified.

All good BUT since you are using arrayFirst it is only creating dependencies on some of the editables (until one with hasChanges=true is found).  Does viewmodel.hasChanges need to use arrayForEach instead?

**Comment by marchenko1985** [comment]
@Brendan-csel acutally nope, arrayFirst do not create any dependencies, it just doing what its name for, here is little [prof](http://jsfiddle.net/mac2000/83ycwa5L/embedded/result,js,html/) no matter in which order you will check/uncheck items, hasChanges will be recalculated accordingly
